### PR TITLE
Add msgfmt test

### PR DESCRIPTION
**Pull request by tschoonj**
This PR serves to demonstrate a problem that was somehow introduced in #12, resulting in msgfmt crashing on Windows when used as part of a conda build (it seems to works fine from a regular environment). The problem was first observed in https://github.com/conda-forge/glib-networking-feedstock/pull/3.

@isuruf @ocefpaf @xhochy

### CODE REVIEW

**Comment by tschoonj** [comment]
This now also occurring in https://github.com/conda-forge/atk-feedstock/pull/17 and will probably pop up in all builds that use gettext on Windows.

**Comment by isuruf** [comment]
There's https://github.com/conda-forge/admin-requests where we can mark a build as broken

**Comment by tschoonj** [comment]
Looks like I fixed things while keeping support for OSX ARM.

One remaining thing to fix is the license: it looks to me that there parts LGPL-2 and other bits are GPL-3... how does one write that down?

**Comment by isuruf** [comment]
`LGPL-2.0-or-later AND GPL-3.0-or-later` (exact version might be different and `-or-later` might need to be changed `-only`)

**Comment by tschoonj** [comment]
Thanks for that. Fixes pushed. Feel free to merge in once everything goes green.

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Review by isuruf — APPROVED** [review]

**Comment by pkgw** [comment]
@tschoonj Is it clear what the actual problem is/was here? From the final diffs, it looks like the main change is to lock to VS 2015?

**Comment by tschoonj** [comment]
Yep that appears to be the culprit. No idea why though.

**Comment by tschoonj** [comment]
Thanks @pkgw and @isuruf!

**Pull request merged**
